# Build settings
#markdown: redcarpet
#highlighter: pygments
highlighter: rouge
gems:
  - jemoji

# Site settings
title: "Jaja Jr. jr. Records"
description: > # this means to ignore newlines until "email:"
   Brooklyn and Rochester, New York.

email: JajaJrjrRecords@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/album-logic.jpg"

name: 'Jaja Jr. jr.'
author: 'Jaja Jr. jr.'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://jajajrjr.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/jajajrjr
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
    target: '_blank'

  - icon:	facebook
    url:	https://www.facebook.com/pages/Jaja-Jr-jr-Records/1618117338461013
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
