# Site settings
title: Jaja Jr. jr. Records
email: JajaJrjrRecords@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jaja Jr. jr. Records (2015) - Khaaaakis, Music, Gear, Soda, Beer, Internet, Websites, NSA, U2, Gowanus Dolphin, Mark Sanchez Jr. jr. and a tasteful amount of Khakis. Hip-hop, folk, electronic, rock and roll.
baseurl: "" # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: JajaJrjr
github_username:  

# Build settings
markdown: kramdown
